language: python

python:
  - 3.6

install:
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install cython
  - pip install qutip

script:
  - python -m unittest discover test
  
